name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'changelog.json'

jobs:

  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            SERVICENAME: emperor_pandas
            CONTAINERFILE: Containerfile-pandas

    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        id: push_image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ${{ matrix.CONTAINERFILE }}
          tags: h0d0user/${{ matrix.SERVICENAME }}:latest

      - name: Notify if failure
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>!!! FAILED !!!</b>
            <b>Failed job:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}


  telegram:
    runs-on: ubuntu-latest
    name: Notification
    needs: [ build ]

    steps:
      - name: Notify telegram message after Packaging
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} created commit:

            <b>WorkFlows:</b> <a href="https://github.com/${{ github.repository }}/actions">ActionsList</a>

            Commit with tag: ${{ needs.prepare.outputs.get_current_tag }}

            Repository: ${{ github.repository }}

            Branch: ${{ github.ref }}

            <b>Pushed image:</b> <code>docker pull h0d0user/emperor_pandas:latest</code>

            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}